export const CATEGORY_LABELS = [
  'Restaurants',
  'Hotels',
  'Things to do',
  'Museums',
  'Transit',
  'Pharmacies',
  'Gyms',
  'Mosques',
  'Parking',
  'Gas Stations',
  'Malls',
] as const;

export type Category = (typeof CATEGORY_LABELS)[number];

export interface PlaceData {
  name: string;
  coords: [number, number];
  type: string;
  address: string;
  image?: string;
  rating?: number;
  reviews?: number;
  about?: string;
  name_ar?: string;
  type_ar?: string;
  address_ar?: string;
  about_ar?: string;
  distance_m?: number;
  category?: Category;
  phone?: string;
  website?: string;
}

export const mockCategoryData: Record<Category, PlaceData[]> = {
  Restaurants: [
    {
      name: 'Najd Village',
      coords: [46.6853, 24.7236],
      rating: 4.6,
      reviews: 3102,
      type: 'Traditional Saudi Restaurant',
      address: 'Abu Bakr Al Siddiq Rd, Riyadh',
      about: 'Authentic Saudi cuisine served in a traditional mud-house setting.',
      image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
      name_ar: 'قرية نجد',
      type_ar: 'مطعم سعودي تقليدي',
      address_ar: 'طريق أبو بكر الصديق، الرياض',
      about_ar: 'مأكولات سعودية أصيلة تُقدَّم في بيئة تراثية بالطين.',
    },
    {
      name: 'The Globe',
      coords: [46.6845, 24.6908],
      rating: 4.8,
      reviews: 1540,
      type: 'Fine Dining',
      address: 'Al Faisaliah Tower, Riyadh',
      about: 'Luxury dining inside the iconic glass sphere with panoramic city views.',
      image: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800&q=80',
      name_ar: 'ذا غلوب',
      type_ar: 'مطعم فاخر',
      address_ar: 'برج الفيصلية، الرياض',
      about_ar: 'تجربة طعام فاخرة داخل الكرة الزجاجية الشهيرة مع إطلالة بانورامية على المدينة.',
    },
  ],
  Hotels: [
    {
      name: 'Four Seasons Riyadh',
      coords: [46.6742, 24.7116],
      rating: 4.7,
      reviews: 2150,
      type: 'Luxury Hotel',
      address: 'Kingdom Centre, Olaya, Riyadh',
      about: 'Premium suites and skyline views in one of Riyadhs most iconic towers.',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      name_ar: 'فور سيزونز الرياض',
      type_ar: 'فندق فاخر',
      address_ar: 'برج المملكة، العليا، الرياض',
      about_ar: 'أجنحة فاخرة وإطلالات خلّابة على أفق المدينة في أحد أبرز أبراج الرياض.',
    },
    {
      name: 'The Ritz-Carlton Riyadh',
      coords: [46.629, 24.664],
      rating: 4.8,
      reviews: 3220,
      type: 'Luxury Resort Hotel',
      address: 'Mekkah Road, Al Hada, Riyadh',
      about: 'Palatial architecture, landscaped gardens, and full-service luxury amenities.',
      image: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80',
      name_ar: 'ريتز كارلتون الرياض',
      type_ar: 'منتجع فندقي فاخر',
      address_ar: 'طريق مكة المكرمة، الهدا، الرياض',
      about_ar: 'هندسة معمارية قصرية وحدائق منسّقة وخدمات فندقية متكاملة.',
    },
  ],
  'Things to do': [
    {
      name: 'Boulevard Riyadh City',
      coords: [46.6046, 24.7686],
      rating: 4.6,
      reviews: 10240,
      type: 'Entertainment District',
      address: 'Hittin, Riyadh',
      about: 'Dining, live shows, and attractions in one of the citys largest event zones.',
      image: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=800&q=80',
      name_ar: 'بوليفارد سيتي الرياض',
      type_ar: 'حي ترفيهي',
      address_ar: 'حي حطين، الرياض',
      about_ar: 'مطاعم وعروض حية ومعالم ترفيهية في واحدة من أكبر مناطق الفعاليات بالمدينة.',
    },
    {
      name: 'Kingdom Centre Sky Bridge',
      coords: [46.6744, 24.7114],
      rating: 4.5,
      reviews: 4210,
      type: 'City Viewpoint',
      address: 'Olaya St, Riyadh',
      about: 'A glass bridge observation deck offering panoramic views of Riyadh.',
      image: 'https://images.unsplash.com/photo-1470004914212-05527e49370b?w=800&q=80',
      name_ar: 'جسر المشاة السماوي - برج المملكة',
      type_ar: 'منصة مشاهدة',
      address_ar: 'شارع العليا، الرياض',
      about_ar: 'جسر زجاجي لمشاهدة البانوراما يوفر إطلالات خلابة على مدينة الرياض.',
    },
  ],
  Museums: [
    {
      name: 'National Museum',
      coords: [46.7106, 24.6475],
      rating: 4.7,
      reviews: 4200,
      type: 'History Museum',
      address: 'King Abdul Aziz Historical Centre',
      about: 'State-of-the-art exhibits detailing the history of the Arabian Peninsula.',
      image: 'https://images.unsplash.com/photo-1580674285054-bed31e145f59?w=800&q=80',
      name_ar: 'المتحف الوطني',
      type_ar: 'متحف تاريخي',
      address_ar: 'مركز الملك عبدالعزيز التاريخي',
      about_ar: 'معروضات متطورة تستعرض تاريخ شبه الجزيرة العربية.',
    },
    {
      name: 'Al Masmak Fortress',
      coords: [46.7133, 24.6311],
      rating: 4.5,
      reviews: 2930,
      type: 'Heritage Museum',
      address: 'Dirah, Riyadh',
      about: 'Historic clay-and-mudbrick fort linked to the founding of modern Saudi Arabia.',
      image: 'https://images.unsplash.com/photo-1577083552431-6e5fd01988f2?w=800&q=80',
      name_ar: 'قصر المصمك',
      type_ar: 'متحف تراثي',
      address_ar: 'الديرة، الرياض',
      about_ar: 'قلعة تاريخية من الطين والآجر ترتبط بتأسيس المملكة العربية السعودية الحديثة.',
    },
  ],
  Transit: [
    {
      name: 'KAFD Metro Station',
      coords: [46.6395, 24.7615],
      rating: 4.4,
      reviews: 980,
      type: 'Metro Station',
      address: 'King Abdullah Financial District, Riyadh',
      about: 'Modern transit hub connecting major business and residential areas.',
      image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80',
      name_ar: 'محطة مترو مركز الملك عبدالله المالي',
      type_ar: 'محطة مترو',
      address_ar: 'مركز الملك عبدالله المالي، الرياض',
      about_ar: 'مركز نقل عصري يربط المناطق التجارية والسكنية الكبرى.',
    },
    {
      name: 'Olaya Station',
      coords: [46.675, 24.705],
      rating: 4.2,
      reviews: 760,
      type: 'Transit Station',
      address: 'Olaya District, Riyadh',
      about: 'Centrally located station with quick access to key routes across Riyadh.',
      image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80',
      name_ar: 'محطة العليا',
      type_ar: 'محطة مواصلات',
      address_ar: 'حي العليا، الرياض',
      about_ar: 'محطة مركزية توفر وصولاً سريعاً إلى أبرز المسارات في الرياض.',
    },
  ],
  Pharmacies: [
    {
      name: 'Nahdi Pharmacy - Olaya',
      coords: [46.6811, 24.7011],
      rating: 4.4,
      reviews: 1180,
      type: 'Pharmacy',
      address: 'Olaya Street, Riyadh',
      about: 'Trusted chain pharmacy with health products and late-night service.',
      image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&q=80',
      name_ar: 'صيدلية النهدي - العليا',
      type_ar: 'صيدلية',
      address_ar: 'شارع العليا، الرياض',
      about_ar: 'سلسلة صيدليات موثوقة تقدم منتجات صحية وخدمة على مدار الليل.',
    },
    {
      name: 'Al-Dawaa Pharmacy',
      coords: [46.6612, 24.7214],
      rating: 4.3,
      reviews: 920,
      type: 'Pharmacy',
      address: 'King Fahd Road, Riyadh',
      about: 'Wide selection of medicines, personal care, and wellness essentials.',
      image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&q=80',
      name_ar: 'صيدلية الدواء',
      type_ar: 'صيدلية',
      address_ar: 'طريق الملك فهد، الرياض',
      about_ar: 'تشكيلة واسعة من الأدوية ومنتجات العناية الشخصية ومستلزمات الصحة.',
    },
  ],
  Gyms: [
    {
      name: 'Fitness Time',
      coords: [46.6653, 24.7136],
      rating: 4.3,
      reviews: 850,
      type: 'Health Club',
      address: 'King Fahd Rd, Riyadh',
      about: 'Premium gym facilities with pools, courts, and personal training.',
      image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
      name_ar: 'فتنس تايم',
      type_ar: 'نادٍ رياضي',
      address_ar: 'طريق الملك فهد، الرياض',
      about_ar: 'مرافق رياضية متميزة تشمل مسابح وملاعب وتدريباً شخصياً.',
    },
    {
      name: 'PureGym',
      coords: [46.655, 24.7],
      rating: 4.2,
      reviews: 640,
      type: 'Fitness Center',
      address: 'Al Woroud District, Riyadh',
      about: 'Modern equipment, strength zones, and flexible membership options.',
      image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80',
      name_ar: 'بيور جيم',
      type_ar: 'مركز لياقة بدنية',
      address_ar: 'حي الورود، الرياض',
      about_ar: 'أجهزة حديثة ومناطق تقوية وخيارات اشتراك مرنة.',
    },
  ],
  Mosques: [],
  Parking: [],
  'Gas Stations': [],
  Malls: [],
};
